### PR TITLE
finish task#19, including user api, &note api, &login

### PR DESCRIPTION
**Pull request by YONGSIGU**
To finish this task, I need to finish the login/user api first because every note should be bound with an user-id. Do I need create another tasks or just leave them in this branch?

1. I have put my test altas db credential in the source code because I create one user already to tst and you can test directly. (although Prof said it should not do this and I will shut-down that test account in next sprint)
2. the user url (create user ... ):
     http://localhost:5000/api/users
3  the login url:
     http://localhost:5000/login
4. the note url:
     http://localhost:5000/api/notes
5. test steps:
    in the back directory:   npm start
    then in other terminal:   
       a.. get the token
              curl -X POST http://localhost:5000/login -H "Content-Type: application/json" -d "{\"Username\": \"testUser\", \"password\": \"testPass\"}" 
       b. create new note
              curl -X POST http://localhost:5000/api/notes -H "Content-Type: application/json" -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwiaWF0IjoxNzMwMDI1Mzg5LCJleHAiOjE3MzAxMTE3ODl9.v5xrWIVp4tr15QHED9vqSwiO6ypBgHBjJK2fCmE9x2M" -d "{\"title\": \"Test Note\", \"content\": \"This is a test note.\", \"tags\": [\"test\", \"note\"]}"

### CODE REVIEW

**Comment by GavinZhengOI** [comment]
Please resolve the conflict first, thanks! @YONGSIGU

**Review by GavinZhengOI — CHANGES_REQUESTED** [review]
Please resolve conflict. Thanks!

**Comment by YONGSIGU** [comment]
conflict solved. please check.

**Review by AndrewJ1234 — APPROVED** [review]
Everything looks good! Thank you zuyuan

**Review by GavinZhengOI — APPROVED** [review]

**Pull request merged**
